version: 2
updates:
  - package-ecosystem: github-actions
    directory: .github/workflows
    schedule:
      interval: weekly
    assignees:
      - lycantropos
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    assignees:
      - lycantropos
    groups:
      non-major:
        update-types:
          - patch
          - minor
  - package-ecosystem: rust-toolchain
    directory: /
    schedule:
      interval: weekly
    assignees:
      - lycantropos
    groups:
      non-major:
        update-types:
          - patch
          - minor
